# Generated by Django 5.2.4 on 2025-07-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmbcChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustingTube', models.CharField(max_length=100)),
                ('cylinderBody', models.CharField(max_length=100)),
                ('bracket', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftWheel', models.CharField(max_length=100)),
                ('rightWheel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheelType', models.CharField(max_length=100)),
                ('diameter', models.FloatField()),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('inspectedBy', models.CharField(max_length=100)),
                ('bmbcChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bmbcchecksheet')),
                ('wheelAssembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.wheelassembly')),
            ],
        ),
    ]
